# Generated by Django 5.2 on 2025-05-22 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0002_alter_profile_profileimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
