# Generated by Django 5.2 on 2025-06-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0012_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Launchpad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=600)),
                ('company_name', models.CharField(max_length=600)),
                ('date', models.CharField(max_length=600)),
                ('location_point', models.CharField(max_length=600)),
                ('product_description', models.CharField(max_length=600)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='launchpad_images/')),
                ('product_link', models.CharField(max_length=600)),
            ],
        ),
    ]
