# Generated by Django 5.2 on 2025-06-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0013_launchpad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchpad',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
