# Generated by Django 5.2 on 2025-06-25 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0018_blackfridaydeal_alter_launchpad_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchpad',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launchpads', to=settings.AUTH_USER_MODEL),
        ),
    ]
