# Generated by Django 5.2 on 2025-06-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0019_alter_launchpad_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackfridaydeal',
            name='change',
            field=models.IntegerField(blank=True, help_text='Use negative numbers to subtract or positive to restock', null=True),
        ),
        migrations.AlterField(
            model_name='blackfridaydeal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blackfridaydeal',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
