# Generated by Django 5.2.4 on 2025-07-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0027_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='david.tag'),
        ),
    ]
