# Generated by Django 5.2.4 on 2025-07-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0029_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='categories',
            field=models.ManyToManyField(related_name='tags', to='david.category'),
        ),
    ]
