# Generated by Django 5.2.4 on 2025-07-22 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0033_remove_post_media_postmedia_delete_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='david.category'),
        ),
    ]
