# Generated by Django 5.2.4 on 2025-07-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0035_profile_security_answer_profile_security_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='security_answer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='security_question',
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
